### ISSUE TITLE
New API key Requirement on PnW

### ISSUE THREAD

**Issue by schmitt07** [PDun/PoliticsAndWarAPIAccess#6]
I have been using this for a while and it has always worked until the new update Alex pushed through to the game, all endpoints now require an API key to work, so none of the gets you put in work anymore. I think they need a variable in the get methods for the API key and then push them through with the new URLs. Are you updating for these new changes?

**Comment by PDun** [comment]
Yes, I had worked on the updates but wanted to verify after the change was in effect. Will get something published out soon with it.

**Comment by schmitt07** [comment]
Ah no problem, no rush for me as it is not being heavily used yet on my discord bot I am using it on. Just wanted to make sure it was happening.

**Comment by PDun** [comment]
Fixed with version 1.0.23 on Nuget.
